name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Install Dependencies
        run: npm install
      
      - name: Run Tests
        run: npm test -- --coverage
        env:
          CI: true
      
      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: coverage/

  build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install
      
      - name: Build
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: dist/

  notification:
    runs-on: ubuntu-latest
    needs: [tests, build]
    steps:
      - name: Send Notification Email
        env:
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
        run: |
          echo "Pipeline executed successfully!" | mail -s "CI/CD Pipeline Notification" $EMAIL_RECIPIENT
