name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/checkout@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Test with Maven
      run: |
        cd Aula-GitHub-Actions
        mvn clean test site

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

  notification:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Notification 
  
        run: |
          chmod +x scripts/shell.sh
          export EMAIL_NOTIFICATION=$EMAIL_NOTIFICATION
          ./scripts/shell.sh
        env:
          EMAIL_NOTIFICATION: ${{ secrets.EMAIL_NOTIFICATION }}
